### ISSUE TITLE
Tradeoff Analytics results do not load

### ISSUE THREAD

**Issue by jakepeyser** [germanattanasio/nycschoolfinder#1]
When I analyze my text, I get the Personality Insights results back, but the Tradeoff Analytics UI continues to infinitely show the loading gif. The console shows the following error, which may be related:

![image](https://cloud.githubusercontent.com/assets/1534503/10054731/3c126894-61f8-11e5-8cc0-7a32190c9bc6.png)

**Comment by germanattanasio** [comment]
Fixed.
